# Starting Pandas 

# Padas Series

In [ ]:
-- One Dimension = Series
-- Two Dimension = Data Frames

In [4]:
import pandas as pd
import numpy as np


In [7]:
list_1 = [1,2,3,4,5,6]
list_2 = ['Rajeev','Rakesh','Mohan','Subham']

In [8]:
series = pd.Series(list_1)
series2 = pd.Series(list_2, index=['a','b','c','d'])
print(series)
print('-------------')
print(series2)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
-------------
a    Rajeev
b    Rakesh
c     Mohan
d    Subham
dtype: object


In [11]:
dict_1 = {
    'a':1,
    'b':2,
    'c':3,
    'd':4,
    'e':5
}

In [34]:
dic_series = pd.Series(dict_1)
print(dic_series.to_list())
print(dic_series.loc['a':'e'])
print(dic_series.iloc[0:5])

[1, 2, 3, 4, 5]
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [15]:
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [16]:
series[3]

np.int64(4)

In [30]:
series[0:6:2]

0    1
2    3
4    5
dtype: int64

In [9]:
arr1=  np.array(list_1)
print(arr1)

[1 2 3 4 5 6]


In [10]:
arrSeries = pd.Series(arr1)


In [12]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr2Series = pd.DataFrame(arr2)
print(arr2Series)

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


# Data Frames

In [14]:
data_frame = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]] )
data_frame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
data_frame2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A','B','C'])
data_frame2

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
df_dic = {
    'Name':['Rajeev','Rohan','Mukesh'],
    'Roll No.':[123,456,789,],
    'City':['GGN','DEL','MUM',]
}
df = pd.DataFrame(df_dic)
df

Name  Roll No. City
0  Rajeev       123  GGN
1   Rohan       456  DEL
2  Mukesh       789  MUM

In [25]:
employees_data = pd.read_csv("C:/Data Analytics/MySql/Practice/ST - SQL ALL PRACTICE FILES/All Excel Practice Files/employee_data.csv")
employees_data


employee_id first_name  last_name                     email  department  \
0              1     Joshua      Ramos     alexandra29@gmail.com  Operations   
1              2  Christina      Clark      littlekyle@yahoo.com          IT   
2              3   Jonathon   Sullivan    tannerivan@johnson.com  Operations   
3              4    Clinton    Aguirre     jamieortega@yahoo.com          HR   
4              5   Veronica      Weber   trevinosteven@ramos.com  Operations   
..           ...        ...        ...                       ...         ...   
995          996     Brandi      Cowan        qsimmons@gmail.com     Finance   
996          997    Michael       Gray     curtisruben@gmail.com          IT   
997          998  Cassandra  Rodriguez  brittneytran@dunlap.info     Finance   
998          999      April     Howard    crystalcohen@smith.com  Operations   
999         1000   Benjamin     Palmer  darylsnyder@williams.com          IT   

       salary joining_date  age  
0    65313.80   2024-05-23   42  
1    58827.32   2021-10-02   46  
2    57427.31   2020-04-30   50  
3    45352.74   2021-04-04   55  
4    78772.56   2020-10-06   51  
..        ...          ...  ...  
995  97102.57   2024-11-07   41  
996  40509.73   2023-03-11   37  
997  72886.03   2024-07-25   32  
998  32177.63   2022-04-06   29  
999  87670.82   2020-04-03   38  

[1000 rows x 8 columns]

In [26]:
employees_data.shape

(1000, 8)

In [27]:
employees_data.dtypes

employee_id       int64
first_name       object
last_name        object
email            object
department       object
salary          float64
joining_date     object
age               int64
dtype: object

In [28]:
employees_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   employee_id   1000 non-null   int64  
 1   first_name    1000 non-null   object 
 2   last_name     1000 non-null   object 
 3   email         1000 non-null   object 
 4   department    1000 non-null   object 
 5   salary        1000 non-null   float64
 6   joining_date  1000 non-null   object 
 7   age           1000 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 62.6+ KB


In [35]:
employees_data.iloc[0:5,1:4]

first_name last_name                    email
0     Joshua     Ramos    alexandra29@gmail.com
1  Christina     Clark     littlekyle@yahoo.com
2   Jonathon  Sullivan   tannerivan@johnson.com
3    Clinton   Aguirre    jamieortega@yahoo.com
4   Veronica     Weber  trevinosteven@ramos.com

In [37]:
employees_data.loc[:10,'department':'age']

department    salary joining_date  age
0   Operations  65313.80   2024-05-23   42
1           IT  58827.32   2021-10-02   46
2   Operations  57427.31   2020-04-30   50
3           HR  45352.74   2021-04-04   55
4   Operations  78772.56   2020-10-06   51
5      Finance  30448.72   2020-05-05   41
6    Marketing  88476.72   2020-10-15   48
7    Marketing  49895.55   2021-06-08   33
8      Finance  88878.64   2024-07-17   47
9           HR  88331.24   2020-03-23   38
10   Marketing  68588.45   2020-07-21   26

In [38]:
employees_data.columns

Index(['employee_id', 'first_name', 'last_name', 'email', 'department',
       'salary', 'joining_date', 'age'],
      dtype='object')